apiVersion: apps/v1
kind: Deployment
metadata:
  name: phongthuy-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # --- THÊM 2 DÒNG NÀY VÀO ĐÂY ---
      imagePullSecrets:
      - name: ghcr-login-secret
      # -------------------------------
      containers:
      - name: frontend
        image: ghcr.io/oppathang/my-app/phongthuy-frontend:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
